# Generated by Django 3.1 on 2022-05-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220523_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountpost',
            name='content',
            field=models.TextField(blank=True, max_length=2048, verbose_name='Содержание'),
        ),
    ]
