# Generated by Django 3.1 on 2022-05-22 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import organization.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование организации')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефона')),
                ('is_activated', models.BooleanField(db_index=True, default=True, verbose_name='Активное')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('description', models.TextField(blank=True, verbose_name='Описание организации')),
                ('image', models.ImageField(blank=True, upload_to=organization.models.image_url_main, verbose_name='Изображение')),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='main.location', verbose_name='Расположение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='OrganizationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Наименование категории организации')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории организации')),
            ],
            options={
                'verbose_name': 'Категория организации',
                'verbose_name_plural': 'Категории организаций',
            },
        ),
        migrations.CreateModel(
            name='OrganizationPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, upload_to=organization.models.image_url, verbose_name='Изображение')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Пост организации',
                'verbose_name_plural': 'Посты организации',
            },
        ),
        migrations.CreateModel(
            name='COrganizationAndOrganizationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FKOrganization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organization', verbose_name='Организация')),
                ('FKOrganizationCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organizationcategory', verbose_name='Категория Организации')),
            ],
            options={
                'verbose_name': 'Связь Организация и Категория организации',
                'verbose_name_plural': 'Связь Организация и Категория организации',
            },
        ),
    ]
