# Generated by Django 3.1 on 2022-05-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.ManyToManyField(to='organization.OrganizationCategory', verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='COrganizationAndOrganizationCategory',
        ),
    ]
