# Generated by Django 3.1 on 2022-05-19 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationClass',
            new_name='OrganizationCategory',
        ),
    ]
