# Generated by Django 3.1 on 2022-05-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20220519_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Расположение'),
        ),
    ]
