# Generated by Django 3.1 on 2022-05-26 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_service_servicecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0002_auto_20220525_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='master',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='master.master', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
