# Generated by Django 3.1 on 2022-05-31 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_auto_20220530_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscriber',
            new_name='subscriper',
        ),
    ]
