# Generated by Django 3.1 on 2022-05-25 03:30

from django.db import migrations, models
import django.db.models.deletion
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Наименование категории услуг')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории услуг')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Наименование услуги')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание услуги')),
                ('custom_category', models.CharField(blank=True, max_length=255, verbose_name='Пользовательская категория')),
                ('image', models.ImageField(blank=True, upload_to=master.models.image_url_service, verbose_name='Изображение')),
                ('master', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='master.master', verbose_name='Мастер')),
                ('serviceCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.servicecategory', verbose_name='Категория услуг')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
