# Generated by Django 3.1 on 2022-06-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_service_servicecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterpost',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='masterpost',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
    ]
