# Generated by Django 3.1 on 2022-05-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220516_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Выберите пол'), ('m', 'мужской'), ('w', 'женский')], default=None, max_length=30, null=True, verbose_name='Пол'),
        ),
    ]
