# Generated by Django 3.1 on 2022-05-17 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220516_1820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
