# Generated by Django 3.1 on 2022-05-18 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
